MHA/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;

namespace MHA.Models
{
    public class HomeModel
    {
        public ImageBlock ImageBlock { get; set; }
        public InformationBlock InformationBlock { get; set; }
        public CarouselBlock CarouselBlock { get; set; }
        public LocationBlock LocationBlock { get; set; }
        public RegisterBlock RegisterBlock { get; set; }
    }

    public class ImageBlock
    {
        public string MainImageUrl { get; set; }
        public string BoxTitle { get; set; }
        public string BoxText { get; set; }
        public string ButtonText { get; set; }
    }

    public class InformationBlock
    {
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Heading { get; set; }
        public string Text { get; set; }
    }

    public class CarouselBlock
    {
        public string CarouselTitle { get; set; }
        public List<CarouselItem> CarouselItems { get; set; }
    }

    public class CarouselItem
    {
        public string ItemImageUrl { get; set; }
        public string ItemTitle { get; set; }
        public string ItemText { get; set; }
    }

    public class LocationBlock
    {
        public string LocationName { get; set; }
        public string Subtitle { get; set; }
        public string Text { get; set; }
        public string MapPath { get; set; }
        public string GoogleMapsUrl { get; set; }
    }

    public class RegisterBlock
    {
        public string BoxTitle { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string JotFormId { get; set; }

    }

    public class ThankYouModel
    {
        public string InsertIntoPageHead { get; set; }
        public string HomePageRedirect { get; set; }
    }

    public class NotFound
    {
        public string Image { get; set; }
        public string ImageTitle { get; set; }
        public string ImageMainText { get; set; }
    }

}

MHA/Controllers/SurfaceControllers/HomeSurfaceController.cs
using System;
using System.Web.Mvc;
using MHA.Infrastructure;
using Umbraco.Web;

namespace MHA.Controllers.SurfaceControllers
{
    public class HomeSurfaceController : Umbraco.Web.Mvc.SurfaceController
    {
        public ActionResult RenderHome()
        {
            var factory = new Factory();
            var model = factory.HomeModelBuilder(CurrentPage.Id);
            return PartialView("HomePartial", model);
        }

        public ActionResult RenderThankYou()
        {
            var factory = new Factory();
            var model = factory.ThankYouModelBuilder();
            return View("ThankYou", model);
        }

        [ChildActionOnly]
        public ActionResult RenderNotFound()
        {
            var factory = new Factory();
            var model = factory.NotFoundBuilder(CurrentPage.Id);
            return PartialView("NotFound", model);
        }

    }
}

MHA/Views/Base.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>MHA / Bringing quality to later life</title>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/global.css" rel="stylesheet">
    <link href="/css/typography.css" rel="stylesheet">
    <link href="/css/slider.css" rel="stylesheet">
    <link href="/css/mediaQueries.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <script type="text/javascript" src="http://fast.fonts.net/jsapi/d0d4183c-fedc-47b0-bd88-5ee097b1ab73.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="http://fast.fonts.net/jsapi/d0d4183c-fedc-47b0-bd88-5ee097b1ab73.js"></script>


    <!--Jot form code-->
    <script src="https://cdn.jotfor.ms/js/vendor/maskedinput.min.js?v=3.3.12975" type="text/javascript"></script>
    <script src="https://cdn.jotfor.ms/static/prototype.forms.js" type="text/javascript"></script>
    <script src="https://cdn.jotfor.ms/static/jotform.forms.js?3.3.12961" type="text/javascript"></script>
    <script type="text/javascript">
        JotForm.init(function () {
            JotForm.setInputTextMasking('input_15', '##/##/####');
            setTimeout(function () { $('input_4').hint('ex: myname@example.com'); }, 20);
            JotForm.clearFieldOnHide = "disable";
            JotForm.onSubmissionError = "jumpToFirstError";
        });
    </script>

    <link href="/css/JotForm/jotform.css" rel="stylesheet">
    <link href="/css/JotForm/nova.css" rel="stylesheet">
    <link href="/css/JotForm/custom.css" rel="stylesheet">


    <style type="text/css">
        /*.form-label-left {
            width: 150px !important;
        }*/

        .form-line {
            padding-top: 12px;
            padding-bottom: 12px;
        }

        .form-radio-item label,
        .form-checkbox-item label,
        .form-grading-label,
        .form-header {
            color: #555;
        }
    </style>
    <!--Jot form code end-->

</head>
<body>
    @RenderBody()
    <!-- Navigation is hidden for Phase 1

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div>
          </div>

        </nav>-->
    <div class="bottomMenu default-color text-center" style="padding-bottom:10px;"><a href="#bottom" id="top" class="btn btn-lg btn-default uppercase bg-magenta default-white" style="margin-top: 10px">REGISTER YOUR INTEREST</a></div>
    <!-- /******** HIDDEN DIV ********/ -->
    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @*<script type="text/javascript">
        $("#61191590166355").submit(function (ev) { ev.preventDefault(); });
        $("#submit").on("click", function () {

            var bootstrapValidator = $("#61191590166355").data('bootstrapValidator');
            bootstrapValidator.validate();
            if (bootstrapValidator.isValid())
                $("#61191590166355").submit();
            else return;

        });
        </script>*@


    <script src="/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Scripts/scripts.js"></script>
    <script type="text/javascript">

        $(document).scroll(function () {
            var y = $(this).scrollTop();
            if (y > 400) {
                $('.bottomMenu').fadeIn();
            } else {
                $('.bottomMenu').fadeOut();
            }

        });

        $(document).ready(function () {
            if ($("#carousel-indicator").children().length == 1) {
                $("#carousel-indicator").css("display", "none");
                $("#left-carousel-arrow").css("display", "none");
                $("#right-carousel-arrow").css("display", "none");
            };

            if ($(".field-validation-error")[0]) {
                document.getElementById("bottom").scrollIntoView();
            }

            $('.field-validation-error').each(function () {
                $(this).css("color", "red");
            });

        });
    </script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

    @Html.Raw(Model.Content.GetPropertyValue("insertIntoPageBody"))


</body>
</html>

MHA/Views/Home.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Base.cshtml";
}

@Html.Action("RenderHome","HomeSurface")
		
	

MHA/Views/Partials/CarouselPartial.cshtml
@model MHA.Models.HomeModel

<div>
    <div class="row bg-sand-biege">
        <div class="container padding-x50">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="primary-size color-magenta font-xx-large uppercase">@Model.CarouselBlock.CarouselTitle</h2>
                    <hr>
                </div>
            </div>
            <div class="col-md-12">
                <div id="myCarousel" class="carousel slide">
                    <ol id="carousel-indicator" class="carousel-indicators">
                        @*<li data-target="#myCarousel" data-slide-to="0" class="active"></li>*@
                        @{
                            var carouselCount = 1;
                            var panelCount = 1;
                        }
                        @foreach (var carouselItem in Model.CarouselBlock.CarouselItems)
                        {
                            @*if (carouselCount != 1 && carouselCount % 4 == 1)
                            {
                                <li data-target="#myCarousel" data-slide-to="@panelCount"></li>
                                panelCount++;
                            }
                            carouselCount++;*@
                        }
                    </ol>
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="row">
                                @{
                                    carouselCount = 0;
                                }

                                @foreach (var carouselItem in Model.CarouselBlock.CarouselItems)
                                {
                                    if (carouselCount != 0 && carouselCount % 4 == 0)
                                    {
                                        @:</div>
                                        @:</div>
                                        @:<div class="item">
                                        @:<div class="row">
                                    }                            
                                    carouselCount++;
                                    <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                                        <img class="thumbnail" src="@carouselItem.ItemImageUrl" alt="Image" style="width:100%;">
                                        <span class="carousel-header color-magenta medium bold">@carouselItem.ItemTitle</span>
                                        <p>@carouselItem.ItemText</p>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                @*<a data-slide="prev" href="#myCarousel" id="left-carousel-arrow" class="left carousel-control"><i class="fa fa-angle-left fa-4"></i></a>*@
                @*<a data-slide="next" href="#myCarousel" id="right-carousel-arrow" class="right carousel-control"><i class="fa fa-angle-right fa-4"></i></a>*@
            </div>
        </div>
    </div>
</div>

MHA/Views/Partials/HomePartial.cshtml
@model MHA.Models.HomeModel

<div class="wrapper">
    @Html.Partial("ImagePartial", Model)
    @Html.Partial("InformationPartial", Model)
    @Html.Partial("CarouselPartial", Model)
    @Html.Partial("LocationPartial", Model)
    @Html.Partial("RegisterPartial", Model)

    <!-- WRAPPER CLOSE -->
    <div class="push"></div>

    <!-- /******** footer component DESKTOP ONLY ********/ -->
    <div class="footer hidden-sm hidden-xs">
        <div class="container padding-x20">
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-inline">
                        <li><a href="#">&copy;&nbsp;2018 MHA&nbsp;&nbsp;&nbsp;</a></li>
                        <!--<li><a href="#">Terms & Conditions&nbsp;&nbsp;&nbsp;</a>&#124;</li>
                        <li><a href="#">Privacy</a></li>-->
                    </ul>
                </div>
                <div class="col-md-6 pull-right">
                    <p>MHA is a Registered Charity in England & Wales (No. 1083995). Company limited by Guarantee (No. 4043124). Registered Office: MHA, Epworth House, Stuart Street, Derby, DE1 2EQ</p>
               </div>
            </div>
        </div>
    </div>
    <!-- /******** footer component MOBILE ONLY *********/ -->
    <div class="footer visible-sm visible-xs text-center">
        <div class="container padding-x20">
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-inline">
                        <li><a href="#">&copy;&nbsp;2018 MHA&nbsp;&nbsp;&nbsp;</a></li>
                        <!--<li><a href="#">Terms & Conditions&nbsp;&nbsp;&nbsp;</a>&#124;</li>
                        <li><a href="#">Privacy</a></li>-->
                    </ul>
                </div>
                <div class="col-md-6  text-center">
                    <p>MHA is a Registered Charity in England & Wales (No. 1083995). Company limited by Guarantee (No. 4043124). Registered Office: MHA, Epworth House, Stuart Street, Derby, DE1 2EQ</p>
                   
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- /******** footer component ********/ -->
    <!-- /.container -->
</div>

MHA/Views/Partials/ImagePartial.cshtml
@model MHA.Models.HomeModel

<!-- /******** Header component ********/ -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 component-header">
        <div class="text-center "><a href="http://www.mha.org.uk" target="_blank"><img src="/img/brand.jpg" height="75" width="124" class="fade-me-hover"></a></div>
    </div>
</div>

<!-- /******** Header component ********/ -->
<div class="row">
    <div class="col-md-12 header-img">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 text-center nested-header padding-0 nested-block">
                <div class="col-md-12 col-sm-12 nested-bar bg-magenta">
                    <p class="primary-size default-white uppercase font-x-large">@Model.ImageBlock.BoxTitle</p>
                </div>
                <div class="nested-panel">
                    @Model.ImageBlock.BoxText
                    <p class="padding-x10">
                        <a href="#bottom" id="top" class="btn btn-lg btn-default uppercase bg-magenta default-white" style="margin-top: 10px;">@Model.ImageBlock.ButtonText</a>&nbsp;
                        <a href="/maidment_sales.html" class="btn btn-lg btn-default uppercase bg-magenta default-white" style="margin-top: 10px;">Sales Brochure</a>&nbsp;
                        <a href="/maidment_site.html"class="btn btn-lg btn-default uppercase bg-magenta default-white" style="margin-top: 10px;">Site Plan Brochure</a>
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>

MHA/Views/Partials/InformationPartial.cshtml
@model MHA.Models.HomeModel
    
<div class="container padding-x20">
    <div class="starter-template">
        <h2 class="primary-size color-magenta font-xx-large uppercase">@Model.InformationBlock.Title</h2>
        <h3 class="secondary-size color-savannah-biege font-x-large uppercase padding-x5">@Model.InformationBlock.Subtitle</h3>
        <hr>
        <h4 class="color-savannah-biege font-large">
            @Model.InformationBlock.Heading
        </h4>
        @Html.Raw(Model.InformationBlock.Text)
    </div>
</div>

MHA/Views/Partials/LocationPartial.cshtml
@model MHA.Models.HomeModel

<div class="container padding-x50">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="primary-size color-magenta font-xx-large uppercase">Development Location</h2>
            <h3 class="secondary-size color-savannah-biege font-x-large uppercase padding-x5">@Model.LocationBlock.LocationName</h3>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-center">
            <h4 class="color-savannah-biege font-large">@Model.LocationBlock.Subtitle</h4>
            @Html.Raw(Model.LocationBlock.Text)
        </div>
        <div class="col-md-6 col-xs-12">
            <a href="@Model.LocationBlock.GoogleMapsUrl" target="_blank">
                <img src="@Model.LocationBlock.MapPath" class="img-responsive fade-me-hover">
            </a>
        </div>
    </div>
</div>

MHA/Views/Shared/ThankYou.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="">
    <meta http-equiv="refresh" content="3;URL=/">
    <link rel="icon" href="../../favicon.ico">
    <title>MHA / Thank you</title>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/global.css" rel="stylesheet">
    <link href="/css/typography.css" rel="stylesheet">
    <link href="/css/slider.css" rel="stylesheet">
    <link href="/css/mediaQueries.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <script type="text/javascript" src="http://fast.fonts.net/jsapi/d0d4183c-fedc-47b0-bd88-5ee097b1ab73.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="http://fast.fonts.net/jsapi/d0d4183c-fedc-47b0-bd88-5ee097b1ab73.js"></script>
    @Html.Raw(Model.Content.GetPropertyValue("insertIntoPageHead"))
</head>

<style type="text/css">
    .thank-you {
        background: url(../img/hero-1.jpg) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>

<body class="thank-you">

    <div class="row humanist-roman">
        <div class="col-md-12">
            <div class="row thank-you-top">
                <div class="col-md-12 bg-magenta default-white">
                    <div class="error-template humanist-light">
                        <h1 class="bold">
                            Thank you for registering!
                        </h1>
                        <h2>
                            We will be in touch very shortly...
                        </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Scripts/scripts.js"></script>
    <script type="text/javascript">

        $(document).scroll(function () {
            var y = $(this).scrollTop();
            if (y > 400) {
                $('.bottomMenu').fadeIn();
            } else {
                $('.bottomMenu').fadeOut();
            }

        });

        $(document).ready(function () {
            if ($("#carousel-indicator").children().length == 1) {
                $("#carousel-indicator").css("display", "none");
                $("#left-carousel-arrow").css("display", "none");
                $("#right-carousel-arrow").css("display", "none");
            };

            if ($(".field-validation-error")[0]) {
                document.getElementById("bottom").scrollIntoView();
            }

            $('.field-validation-error').each(function () {
                $(this).css("color", "red");
            });

        });
    </script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

  

@Html.Raw(Model.Content.GetPropertyValue("insertIntoPageBody"))
</body>